namespace CommunityToolkit.Aspire.Hosting.JavaScript;

/// <summary>
/// Generates a TypeScript declaration file that augments the
/// <c>NodeJS.ProcessEnv</c> interface for Node.js applications
/// (Express, Fastify, etc.).
/// All (filtered) environment variables are included.
/// </summary>
public sealed class NodeEnvironmentTypeGenerator : IEnvironmentTypeGenerator
{
    /// <summary>
    /// Initializes a new instance of <see cref="NodeEnvironmentTypeGenerator"/>.
    /// </summary>
    /// <param name="outputPath">
    /// Output file path, relative to the working directory
    /// (default: <c>"aspire-env.d.ts"</c>).
    /// </param>
    public NodeEnvironmentTypeGenerator(string outputPath = "aspire-env.d.ts")
    {
        ArgumentException.ThrowIfNullOrEmpty(outputPath);
        OutputPath = outputPath;
    }

    /// <inheritdoc/>
    public string OutputPath { get; }

    /// <inheritdoc/>
    public async Task GenerateAsync(
        string workingDirectory,
        IReadOnlyList<string> environmentVariables,
        CancellationToken cancellationToken = default)
    {
        var writer = new System.Text.StringBuilder();

        writer.AppendLine("// Auto-generated by Aspire — do not edit manually.");
        writer.AppendLine("// Regenerated each time the dev server starts.");
        writer.AppendLine();
        writer.AppendLine("declare namespace NodeJS {");
        writer.AppendLine("    interface ProcessEnv {");

        foreach (var variable in environmentVariables)
        {
            writer.AppendLine($"        {variable}?: string;");
        }

        writer.AppendLine("    }");
        writer.AppendLine("}");

        var outputFile = Path.Combine(workingDirectory, OutputPath);

        Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

        await File.WriteAllTextAsync(outputFile, writer.ToString(), cancellationToken)
            .ConfigureAwait(false);
    }
}
