namespace CommunityToolkit.Aspire.Hosting.JavaScript;

/// <summary>
/// Generates TypeScript declaration modules for SvelteKit's
/// <c>$env/static/private</c>, <c>$env/static/public</c>,
/// <c>$env/dynamic/private</c>, and <c>$env/dynamic/public</c>
/// virtual modules.
/// </summary>
public sealed class SvelteKitEnvironmentTypeGenerator : IEnvironmentTypeGenerator
{
    private readonly string _publicPrefix;

    /// <summary>
    /// Initializes a new instance of <see cref="SvelteKitEnvironmentTypeGenerator"/>.
    /// </summary>
    /// <param name="publicPrefix">
    /// Prefix that marks a variable as publicly accessible from the browser
    /// (default: <c>"PUBLIC_"</c>).
    /// </param>
    /// <param name="outputPath">
    /// Output file path, relative to the working directory
    /// (default: <c>"src/aspire-env.d.ts"</c>).
    /// </param>
    public SvelteKitEnvironmentTypeGenerator(
        string publicPrefix = "PUBLIC_",
        string outputPath = "src/aspire-env.d.ts")
    {
        ArgumentException.ThrowIfNullOrEmpty(publicPrefix);
        ArgumentException.ThrowIfNullOrEmpty(outputPath);

        _publicPrefix = publicPrefix;
        OutputPath = outputPath;
    }

    /// <inheritdoc/>
    public string OutputPath { get; }

    /// <inheritdoc/>
    public async Task GenerateAsync(
        string workingDirectory,
        IReadOnlyList<string> environmentVariables,
        CancellationToken cancellationToken = default)
    {
        var publicVars = environmentVariables
            .Where(v => v.StartsWith(_publicPrefix, StringComparison.Ordinal))
            .ToList();

        var privateVars = environmentVariables
            .Where(v => !v.StartsWith(_publicPrefix, StringComparison.Ordinal))
            .ToList();

        var writer = new System.Text.StringBuilder();

        writer.AppendLine("// Auto-generated by Aspire — do not edit manually.");
        writer.AppendLine("// Regenerated each time the dev server starts.");
        writer.AppendLine();

        AppendStaticModule(writer, "$env/static/private", privateVars);
        writer.AppendLine();
        AppendStaticModule(writer, "$env/static/public", publicVars);
        writer.AppendLine();
        AppendDynamicModule(writer, "$env/dynamic/private", privateVars);
        writer.AppendLine();
        AppendDynamicModule(writer, "$env/dynamic/public", publicVars);

        var outputFile = Path.Combine(workingDirectory, OutputPath);

        Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

        await File.WriteAllTextAsync(outputFile, writer.ToString(), cancellationToken)
            .ConfigureAwait(false);
    }

    private static void AppendStaticModule(
        System.Text.StringBuilder writer,
        string moduleName,
        IReadOnlyList<string> variables)
    {
        writer.AppendLine($"declare module '{moduleName}' {{");

        foreach (var variable in variables)
        {
            writer.AppendLine($"    export const {variable}: string;");
        }

        writer.AppendLine("}");
    }

    private static void AppendDynamicModule(
        System.Text.StringBuilder writer,
        string moduleName,
        IReadOnlyList<string> variables)
    {
        writer.AppendLine($"declare module '{moduleName}' {{");
        writer.AppendLine("    export const env: {");

        foreach (var variable in variables)
        {
            writer.AppendLine($"        {variable}: string;");
        }

        writer.AppendLine("        [key: string]: string | undefined;");
        writer.AppendLine("    };");
        writer.AppendLine("}");
    }
}
