namespace CommunityToolkit.Aspire.Hosting.JavaScript;

/// <summary>
/// Generates a TypeScript declaration file that augments the
/// <c>ImportMetaEnv</c> interface for Vite-based applications
/// (React, Vue, Svelte with Vite, etc.).
/// Only variables whose names start with the configured prefix
/// (default: <c>"VITE_"</c>) are included, because Vite only
/// exposes those to the client bundle.
/// </summary>
public sealed class ViteEnvironmentTypeGenerator : IEnvironmentTypeGenerator
{
    private readonly string _vitePrefix;

    /// <summary>
    /// Initializes a new instance of <see cref="ViteEnvironmentTypeGenerator"/>.
    /// </summary>
    /// <param name="vitePrefix">
    /// Prefix for client-exposed variables (default: <c>"VITE_"</c>).
    /// </param>
    /// <param name="outputPath">
    /// Output file path, relative to the working directory
    /// (default: <c>"src/aspire-env.d.ts"</c>).
    /// </param>
    public ViteEnvironmentTypeGenerator(
        string vitePrefix = "VITE_",
        string outputPath = "src/aspire-env.d.ts")
    {
        ArgumentException.ThrowIfNullOrEmpty(vitePrefix);
        ArgumentException.ThrowIfNullOrEmpty(outputPath);

        _vitePrefix = vitePrefix;
        OutputPath = outputPath;
    }

    /// <inheritdoc/>
    public string OutputPath { get; }

    /// <inheritdoc/>
    public async Task GenerateAsync(
        string workingDirectory,
        IReadOnlyList<string> environmentVariables,
        CancellationToken cancellationToken = default)
    {
        var viteVars = environmentVariables
            .Where(v => v.StartsWith(_vitePrefix, StringComparison.Ordinal))
            .ToList();

        var writer = new System.Text.StringBuilder();

        writer.AppendLine("// Auto-generated by Aspire — do not edit manually.");
        writer.AppendLine("// Regenerated each time the dev server starts.");
        writer.AppendLine();
        writer.AppendLine("/// <reference types=\"vite/client\" />");
        writer.AppendLine();
        writer.AppendLine("interface ImportMetaEnv {");

        foreach (var variable in viteVars)
        {
            writer.AppendLine($"    readonly {variable}: string;");
        }

        writer.AppendLine("}");
        writer.AppendLine();
        writer.AppendLine("interface ImportMeta {");
        writer.AppendLine("    readonly env: ImportMetaEnv;");
        writer.AppendLine("}");

        var outputFile = Path.Combine(workingDirectory, OutputPath);

        Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

        await File.WriteAllTextAsync(outputFile, writer.ToString(), cancellationToken)
            .ConfigureAwait(false);
    }
}
